### 获取用户信息
POST {{url}}/base-user-service/user/get
token: {{token}}
userId: {{userId}}
companyId: {{companyId}}
shopId: {{shopId}}
warehouseId: {{warehouseId}}
companyName: {{companyName}}
shopName: {{shopName}}
warehouseName: {{warehouseName}}
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "id": 3400518517374977
}

###

